"""init

Revision ID: 39894f04a2f4
Revises: 
Create Date: 2023-10-09 11:01:47.004407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39894f04a2f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
