"""empty message

Revision ID: 85d0bfdc504b
Revises: 39894f04a2f4
Create Date: 2023-10-09 11:10:03.431015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d0bfdc504b'
down_revision = '39894f04a2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=False, comment='email'),
    sa.Column('password', sa.String(), nullable=False, comment='password'),
    sa.Column('nickname', sa.String(), nullable=False, comment='nickname'),
    sa.Column('profile_image_url', sa.String(), nullable=False, comment='profile_image_url'),
    sa.Column('user_token', sa.String(), nullable=False, comment='user_token'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='is_active'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='is_superuser'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='is_verified'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='is_deleted'),
    sa.Column('visited_at', sa.DateTime(), nullable=False, comment='last_login_at'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
